/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/icmpnetworkpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeICMPNetworkPolicies implements ICMPNetworkPolicyInterface
type FakeICMPNetworkPolicies struct {
	Fake *FakeK8sV1alpha1
	ns   string
}

var icmpnetworkpoliciesResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1alpha1", Resource: "icmpnetworkpolicies"}

var icmpnetworkpoliciesKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1alpha1", Kind: "ICMPNetworkPolicy"}

// Get takes name of the iCMPNetworkPolicy, and returns the corresponding iCMPNetworkPolicy object, and an error if there is any.
func (c *FakeICMPNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ICMPNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(icmpnetworkpoliciesResource, c.ns, name), &v1alpha1.ICMPNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ICMPNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of ICMPNetworkPolicies that match those selectors.
func (c *FakeICMPNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ICMPNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(icmpnetworkpoliciesResource, icmpnetworkpoliciesKind, c.ns, opts), &v1alpha1.ICMPNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ICMPNetworkPolicyList{ListMeta: obj.(*v1alpha1.ICMPNetworkPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ICMPNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iCMPNetworkPolicies.
func (c *FakeICMPNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(icmpnetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a iCMPNetworkPolicy and creates it.  Returns the server's representation of the iCMPNetworkPolicy, and an error, if there is any.
func (c *FakeICMPNetworkPolicies) Create(ctx context.Context, iCMPNetworkPolicy *v1alpha1.ICMPNetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.ICMPNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(icmpnetworkpoliciesResource, c.ns, iCMPNetworkPolicy), &v1alpha1.ICMPNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ICMPNetworkPolicy), err
}

// Update takes the representation of a iCMPNetworkPolicy and updates it. Returns the server's representation of the iCMPNetworkPolicy, and an error, if there is any.
func (c *FakeICMPNetworkPolicies) Update(ctx context.Context, iCMPNetworkPolicy *v1alpha1.ICMPNetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.ICMPNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(icmpnetworkpoliciesResource, c.ns, iCMPNetworkPolicy), &v1alpha1.ICMPNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ICMPNetworkPolicy), err
}

// Delete takes name of the iCMPNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeICMPNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(icmpnetworkpoliciesResource, c.ns, name), &v1alpha1.ICMPNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeICMPNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(icmpnetworkpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ICMPNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched iCMPNetworkPolicy.
func (c *FakeICMPNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ICMPNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(icmpnetworkpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ICMPNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ICMPNetworkPolicy), err
}
